"""add_marketing_unsubscribed_to_users

Revision ID: 1c9cc3e95c39
Revises: b3e1f9a2d074
Create Date: 2026-06-13 16:31:29.470509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9cc3e95c39'
down_revision: Union[str, None] = 'b3e1f9a2d074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('marketing_unsubscribed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'marketing_unsubscribed')
    # ### end Alembic commands ###
